sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:george-edison55/precise-backports'
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:george-edison55/precise-backports'
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:george-edison55/precise-backports'
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - cmake-data
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:george-edison55/precise-backports'
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - cmake
            - cmake-data
            - clang-3.7
      env: COMPILER=clang++-3.7

install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev

script:
  - cmake . -DCMAKE_CXX_COMPILER=$COMPILER
  - make
  - make test
