name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download and install Boost
      uses: MarkusJx/install-boost@v2.4.4
      with:
        boost_version: 1.83.0
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: make test
