name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download and install Boost
      run: |
          sudo apt-get -y update
          sudo apt-get -y install libboost-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: make test
